from models.vfe import MeanVFE
from models.backbone_3d import VoxelBackBone8x
from models.height_compression import HeightCompression
from models.ssfa import SSFA
from models.head import MultiGroupHead
from models.rdf_teacher import RDFTeacher
from models.vsa import VoxelSetAbstraction
from models.matcher import Matcher
from models.roi_head import RoIHead